theme = "wearewizards"

[customer]
company = "ACME"
person = "Bob Marley"
email = "boss@acme.com"


[project]
name = "Project X"
description = "Write a proposal tool to generate proposals for we are wizards.
The tool will allow to generate pretty proposals with automatic
summation of work items at different rates."
currency = "£"
discount = 5
worker = 1
start = "2015/03/20"
end = "2015/03/29"
uat_start = "2015/03/29"
uat_end = "2015/03/31"

  [[project.rates]]
  name = "Development"
  amount = 800

  [[project.rates]]
  name = "Project Management"
  amount = 700

  [[project.rates]]
  name = "Design"
  amount = 750

  [[project.deliverables]]
  name = "Fix Facebook and Twitter integration"
  description = "Ensure those are working properly for login and connect."
  estimate = 2
  rate = "Development"
  free = false


  [[project.deliverables]]
  name = "Add a badge list page"
  description = "Add a badge list page in the profile, see screenshot."
  estimate = 0.5
  rate = "Design"
  free = true


  [[project.deliverables]]
  name = "Add a badge list page2"
  description = "Add a badge list page in the profile, see screenshot."
  estimate = 0.5
  rate = "Design"
  free = true

  [[project.deliverables]]
  name = "Add a badge list page4"
  description = "Add a badge list page in the profile, see screenshot."
  estimate = 0.5
  rate = "Design"
  free = true

  [[project.deliverables]]
  name = "Add a badge list page5"
  description = "Add a badge list page in the profile, see screenshot."
  estimate = 0.5
  rate = "Design"
  free = true

  [[project.deliverables]]
  name = "Add a badge list page6"
  description = "Add a badge list page in the profile, see screenshot."
  estimate = 0.5
  rate = "Design"
  free = true
